### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by tmaxmax** [tmaxmax/jslazyiter#6]
# Milestone

This library is mostly supposed to be a port of Rust's iterator library, adapted to the Javascript ecosystem. To contribute, look for an unimplemented iterator method in the list, checkout a branch from develop with the method's name, implement the method and corresponding tests, and open a pull request to branch develop.

Here's what needs to be done for February:

## Port from Rust's Standard Library

- [x] [enumerate](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.enumerate) -> **enumerate** (PR #1)
- [x] [fold](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.fold) -> **fold** (PR #8)
- [x] [for_each](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.for_each) -> **forEach** (PR #9)
- [x] [last](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.last) -> **last** (PR #9)
- [x] [count](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.count) -> **count** (PR #9)
- [x] [find](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.find) -> **find** (PR #10)
- [x] [find_map](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.find_map) -> **findMap** (PR #10)
- [x] [filter](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.filter) -> **filter** (PR #10)
- [x] [filter_map](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.filter_map) -> **filterMap** (PR #10)
- [x] [try_fold](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.try_fold) -> **tryFold** (PR #10)
- [x] [try_for_each](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.try_for_each) -> **tryForEach** (PR #10)
- [x] [map](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.map) -> **map** (PR #11)
- [x] [cmp](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.cmp) -> **cmp** (PR #12)
- [x] [eq](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.eq) -> **eq** (PR #12)
- [x] [ge](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.ge) -> **ge** (PR #12)
- [x] [gt](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.gt) -> **gt** (PR #12)
- [x] [le](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.le) -> **le** (PR #12)
- [x] [lt](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.lt) -> **lt** (PR #12)
- [x] [ne](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.ne) -> **ne** (PR #12)
- [x] [any](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.any) -> **any** (PR #13)
- [x] [all](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.all) -> **all** (PR #13)
- [x] [max](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.max) -> **max** (PR #14)
- [x] [max_by](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.max_by) -> **maxBy** (PR #14)
- [x] [max_by_key](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.max_by_key) -> **maxByKey** (PR #14)
- [x] [min](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.min) -> **min** (PR #14)
- [x] [min_by](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.min_by) -> **minBy** (PR #14)
- [x] [min_by_key](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.min_by_key) -> **minByKey** (PR #14)
- [ ] [position](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.position)
- [ ] [take](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.take)
- [ ] [chain](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.chain)
- [ ] [flat_map](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.flat_map)
- [ ] [take_while](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.take_while)
- [ ] [zip](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.zip)
- [ ] [nth](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.nth)
- [ ] [step_by](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.step_by)
- [ ] [skip_while](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.skip_while)
- [ ] [skip](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.skip)
- [ ] [scan](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.scan)
- [ ] [flatten](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.flatten)
- [ ] [inspect](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.inspect)

*From Nightly*
- [x] [fold_first](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.fold_first) -> **fold1** (PR #9)
- [x] [cmp_by](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.cmp_by) -> **cmpBy** (PR #12)
- [x] [eq_by](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.eq_by) -> **eqBy** (PR #12)
- [ ] [advance_by](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.advance_by)
- [ ] [intersperse](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.intersperse)
- [ ] [intersperse_with](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.intersperse_with)
- [ ] [map_while](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.map_while)
- [ ] [try_find](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.try_find)
- [ ] [is_sorted](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.is_sorted)
- [ ] [is_sorted_by](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.is_sorted_by)
- [ ] [is_sorted_by_key](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.is_sorted_by_key)

### Maybe port

- [x] [partial_cmp](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.partial_cmp) -> not implemented, see PR #12 for reason
- [ ] [sum](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.sum) -> see PR #14
- [ ] [product](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.product) -> see PR #14
- [ ] [fuse](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.fuse) -> see issue #15
- [ ] [size_hint](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.size_hint)
- [ ] [cloned](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.cloned)
- [ ] [copied](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.copied)
- [x] [collect](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.collect) -> **collect** (PR #19)
- [ ] [by_ref](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.by_ref)
- [ ] [rev](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.rev)
- [ ] [rposition](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.rposition)
- [ ] [peekable](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.peekable)
- [ ] [partition](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.partition)
- [x] [unzip](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.unzip) -> **unzip** (PR #19)
- [ ] [cycle](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.cycle)

*From Nightly*
- [x] [partial_cmp_by](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.partial_cmp_by) -> **partialCmpBy** (PR #12)
- [x] [partition_in_place](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.partition_in_place) (Javascript iterators can't be used to mutate iterables, so this can't be implemented)
- [ ] [is_partitioned](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.is_partitioned)
